# test againts this version of Node.js
environment:
   matrix:
   - nodejs_version: "11"

# Install scripts. (runs after repo cloning)
install:
   - ps: Install-Product node $env:nodejs_version
   - npm install

test_script:
   - node --version
   - npm --version
   - npm test

#Don't actually build
build: off
